spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQLHOST:127.0.0.1}:${MYSQLPORT:3306}/${MYSQLDATABASE:projetospring}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:1357}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
